'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace srCiudadano
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="srCiudadano.wsCiudadanoSoap")>  _
    Public Interface wsCiudadanoSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*")>  _
        Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Agregar(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*")>  _
        Function AgregarAsync(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Eliminar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Eliminar(ByVal DNI As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Eliminar", ReplyAction:="*")>  _
        Function EliminarAsync(ByVal DNI As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Actualizar(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar", ReplyAction:="*")>  _
        Function ActualizarAsync(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*")>  _
        Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsCiudadanoSoapChannel
        Inherits srCiudadano.wsCiudadanoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsCiudadanoSoapClient
        Inherits System.ServiceModel.ClientBase(Of srCiudadano.wsCiudadanoSoap)
        Implements srCiudadano.wsCiudadanoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Listar() As System.Data.DataSet Implements srCiudadano.wsCiudadanoSoap.Listar
            Return MyBase.Channel.Listar
        End Function
        
        Public Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements srCiudadano.wsCiudadanoSoap.ListarAsync
            Return MyBase.Channel.ListarAsync
        End Function
        
        Public Function Agregar(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As Boolean Implements srCiudadano.wsCiudadanoSoap.Agregar
            Return MyBase.Channel.Agregar(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion)
        End Function
        
        Public Function AgregarAsync(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As System.Threading.Tasks.Task(Of Boolean) Implements srCiudadano.wsCiudadanoSoap.AgregarAsync
            Return MyBase.Channel.AgregarAsync(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion)
        End Function
        
        Public Function Eliminar(ByVal DNI As Integer) As Boolean Implements srCiudadano.wsCiudadanoSoap.Eliminar
            Return MyBase.Channel.Eliminar(DNI)
        End Function
        
        Public Function EliminarAsync(ByVal DNI As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements srCiudadano.wsCiudadanoSoap.EliminarAsync
            Return MyBase.Channel.EliminarAsync(DNI)
        End Function
        
        Public Function Actualizar(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As Boolean Implements srCiudadano.wsCiudadanoSoap.Actualizar
            Return MyBase.Channel.Actualizar(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion)
        End Function
        
        Public Function ActualizarAsync(ByVal DNI As Integer, ByVal Nombres As String, ByVal ApellidoPaterno As String, ByVal ApellidoMaterno As String, ByVal FechaNacimiento As String, ByVal Sexo As String, ByVal EstadoCivil As String, ByVal Direccion As String) As System.Threading.Tasks.Task(Of Boolean) Implements srCiudadano.wsCiudadanoSoap.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion)
        End Function
        
        Public Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet Implements srCiudadano.wsCiudadanoSoap.Buscar
            Return MyBase.Channel.Buscar(texto, criterio)
        End Function
        
        Public Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements srCiudadano.wsCiudadanoSoap.BuscarAsync
            Return MyBase.Channel.BuscarAsync(texto, criterio)
        End Function
    End Class
End Namespace
