//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reniec.srCiudadano1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srCiudadano1.wsCiudadanoSoap")]
    public interface wsCiudadanoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Agregar(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AgregarAsync(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Eliminar(int DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarAsync(int DNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Actualizar(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizarAsync(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCiudadanoSoapChannel : Reniec.srCiudadano1.wsCiudadanoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCiudadanoSoapClient : System.ServiceModel.ClientBase<Reniec.srCiudadano1.wsCiudadanoSoap>, Reniec.srCiudadano1.wsCiudadanoSoap {
        
        public wsCiudadanoSoapClient() {
        }
        
        public wsCiudadanoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCiudadanoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCiudadanoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCiudadanoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public bool Agregar(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion) {
            return base.Channel.Agregar(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarAsync(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion) {
            return base.Channel.AgregarAsync(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion);
        }
        
        public bool Eliminar(int DNI) {
            return base.Channel.Eliminar(DNI);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsync(int DNI) {
            return base.Channel.EliminarAsync(DNI);
        }
        
        public bool Actualizar(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion) {
            return base.Channel.Actualizar(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsync(int DNI, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string FechaNacimiento, string Sexo, string EstadoCivil, string Direccion) {
            return base.Channel.ActualizarAsync(DNI, Nombres, ApellidoPaterno, ApellidoMaterno, FechaNacimiento, Sexo, EstadoCivil, Direccion);
        }
        
        public System.Data.DataSet Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
    }
}
